### ISSUE TITLE
Falscher Link zu JQuery

### ISSUE THREAD

**Issue by dargmuesli** [kmein/alt-gr#4]
Die JQuery-Datei liegt in `/js/`, es wird aber zum Stammverzeichnis `/` verlinkt.

**Comment by kmein** [comment]
JQuery wird eigentlich nicht gecallt..

**Comment by dargmuesli** [comment]
Dann nimm's raus. Pass nur auf, dass dann die Newsleiste wohl nicht mehr funktionieren wird.
